version: '3'

volumes:
  mongo-data:
    driver: local

services:
  cars-query:
    container_name: cars-query
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - $PORT:$PORT
    external_links:
      - mongodb
    environment:
      - NODE_ENV=development

  mongodb:
    container_name: mongodb
    image: mongo:5.0.2
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=cncoding101
      - MONGO_INITDB_ROOT_PASSWORD=1234abcd
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
