version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=cncoding101
      - MONGO_INITDB_ROOT_PASSWORD=1234abcd
    volumes:
      - ${MONGO_HOST_DATA}/db:/data/db
    ports:
      - '27017:27017'
